### ISSUE TITLE
SCS Vehicle editor doesn't allow the period (.) in the internal name field

### ISSUE THREAD

**Issue by Digital-Trucker** [WerewolfCustoms/ModsStudio2IssueBoard#100]
As stated when editing/adding a vehicle the editor gives the following error:
![MWSnap 2021-03-19, 18_19_15](https://user-images.githubusercontent.com/9503744/111847863-233a3080-88e0-11eb-9d7b-ea4150396c46.png)

**Comment by pete-agreatguy** [comment]
Already reported by m1key. I will delete his bug report (96) as this one is more accurate with included screenshot.

m1key:

When saving the custom xml, loaded from within the MS2 application (load from mod/load from folder)
you get the error seen on image:
https://discord.com/channels/611134812471820348/611170373773295616/814846752984399923

Limitations of characters (12) and not able to have the • makes it impossible to export as it should be.
