### ISSUE TITLE
Feature Request - StreamDeck

### ISSUE THREAD

**Issue by Raiden38** [WerewolfCustoms/ModsStudio2IssueBoard#112]
**Is your feature request related to a problem? Please describe.**
Not a problem, just enhancement

**Describe the solution you'd like**
Your plugin is Awesome, using it everyday! Would like to know it if would be possible to set a button with the speed limit? A round red circle with white middle and black speed limit, just like in the game?
Also, would it be possible to have an icon with dammage, gas and sleep icons, just like at the top of the GPS screen? It just makes the streamdeck more usefull, and it's great to have everything at the same place.

Thanks!

**Comment by WerewolfCustoms** [comment]
Most of the requested features will be added in V.2.0; 👍 
Some will be added in 3.0; 🤷‍♂️

![20210721_171432](https://user-images.githubusercontent.com/8348467/135909900-9061d3a5-001c-4964-bd29-b220563b90b5.jpg)
