### ISSUE TITLE
Streamdeck - Engine status now updated after changing folder

### ISSUE THREAD

**Issue by Raiden38** [WerewolfCustoms/ModsStudio2IssueBoard#113]
**Describe the bug**
I have the engine on/off button and when I go into a subfolder, and come back to it, it's not active, even if the engine is on.

**To Reproduce**
1. Add a engine button to the streamdeck
2. Start the game and start the engine (make sure that the button turn yellow STOP
3. Go into a subfolder
4. Go back the the root folder where the engine button is. It will show as if the engine is stopped

**Expected behavior**
Show stay updated to whatever is in the game.

**Comment by WerewolfCustoms** [comment]
🎉 Fixed :)
Works for switching folders, and also switching pages 👍
