### ISSUE TITLE
Export Options for Export as Folder and Export as Steam Workshop Preparation

### ISSUE THREAD

**Issue by Wachert** [WerewolfCustoms/ModsStudio2IssueBoard#115]
**Describe the solution you'd like**
More Export Options instead of just Export as Mod.

- Export as Folder => without zipping it, just in a Folder
- Export as Steam Workshop Preparation with the needed Files to use it in the SCS Workshop Uploader Tool available for free at Steam

**Describe alternatives you've considered**
Building own Macros and Scripts using Powershell, but that is not useable for technical unknown users.

**Comment by criquio** [comment]
> This is coming in the next version: 🎉
> 
> ![2023-09-05 22_32_09-ATS Mod Project - Mods Studio 2](https://github.com/WerewolfCustoms/ModsStudio2/assets/8348467/7e2af025-b166-4281-9d58-28dfe61271fa)

Glad to know... 🤠
