### ISSUE TITLE
3D Previewer Crashing when the already loaded image gets updated in backend

### ISSUE THREAD

**Issue by Wachert** [WerewolfCustoms/ModsStudio2IssueBoard#116]
**Describe the bug / Reproduce Steps**

1. Create an Image in Photoshop and save it as png, keep ps opened with the image
2. Open up the 3D Preview in ModsStudio2
3. Load a model with that specific image
4. enter photoshop, change something
5. export the image from photoshop and save it as the same file, just overwrite it
6. open up the 3d preview window: you see the updated version of the image on the truck
7. open photoshop again and change another part
8. export again and overwrite the existing file
9. open up the 3d preview again.... and it crashed without any error

It doesn't make any difference if you have the 3d preview not minimzed, when i keep it opened on a 2nd screen, same behaviour.

**Screenshots / Videos**
_Please no comments about my very erotic voice or my state of the art english :D_
https://www.youtube.com/watch?v=UoxMUjSvurY

**Desktop (please complete the following information):**
 - v2021.2

**Comment by pete-agreatguy** [comment]
Very well presented :)
