### ISSUE TITLE
Adding 2 Button to start ETS2 or ATS quickly

### ISSUE THREAD

**Issue by Wachert** [WerewolfCustoms/ModsStudio2IssueBoard#117]
**Is your feature request related to a problem? Please describe.**
Workflow optimisation / laziness ;)

**Describe the solution you'd like**
2 Buttons to quickly start ETS or ATS from MS2 so we don't have to switch to the Steam Client or Taskbar etc...

**Describe alternatives you've considered**
Found none...

**Additional context**
Just add 2 Icons for the games here starting the Steam Version of the game.

![grafik](https://user-images.githubusercontent.com/16701558/122747930-eb9aa600-d28b-11eb-83a1-8126b76deb6a.png)

For ETS2: steam://rungameid/227300
For ATS: steam://rungameid/270880

And as additional Feature: steam://open/screenshots
To open Screenshots

**Comment by pete-agreatguy** [comment]
Vote "No" from me.

Reason:

Users can easily access desktop shortcuts / taskbar shortcuts / steam taskbar menu to launch.

**Comment by WerewolfCustoms** [comment]
I think we can add something in the lines of this request... ;)

**Comment by WerewolfCustoms** [comment]
![RunGame2](https://user-images.githubusercontent.com/8348467/139555570-7a128098-946b-49a6-9f37-161c5aa14b61.png)

We have a **_Run Game_** button now, that runs the game related to the Mod Project that is loaded in MS2.
If there is no project loaded, the button is disabled.
