### ISSUE TITLE
Refrigerated trailer in A.I

### ISSUE THREAD

**Issue by Maddogz1717** [WerewolfCustoms/ModsStudio2IssueBoard#120]
Hello I would like to request the above trailer.Getting board of all A.I running on curtains

thanks Maddogz17

**Comment by WerewolfCustoms** [comment]
Request is for ETS2

**Comment by WerewolfCustoms** [comment]
![ets2_20220214_214656_00](https://user-images.githubusercontent.com/8348467/153944325-98337ffc-56b1-4b1a-840d-d85aa71a792e.png)
