### ISSUE TITLE
Cargo mod template

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#133]
Add a cargo mod template, so users can add cargo (without trailers or containers) to the game.

**Comment by Mike7O** [comment]
curent ContainerCargo creating custom cargoes  **missing body_types: dumper**
just a heads-up, if anything else is missing (curently not on an updated gameversion)

**Comment by WerewolfCustoms** [comment]
This is ready to go in, together with other Cargo related issues. 👍
