### ISSUE TITLE
Resizable tobj window

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#137]
**Is your feature request related to a problem? Please describe.**
Some tobj files require a larger viewing space.

**Describe the solution you'd like**
Having the tobj window allowed to be resizable will resolve this.

**Describe alternatives you've considered**
n/a

**Additional context**
Alex discord server request:

https://discord.com/channels/611134812471820348/611135209525608488/905917760054374530

**Comment by pete-agreatguy** [comment]
Completed.

**Comment by WerewolfCustoms** [comment]
TOBJ Editor is now also a standalone application 👍

**Comment by pete-agreatguy** [comment]
Sweet!
