### ISSUE TITLE
Cargo Containers Items are saved incorrectly

### ISSUE THREAD

**Issue by ValouFCH** [WerewolfCustoms/ModsStudio2IssueBoard#145]
When saving a project containing a Cargo Container, it seems that the Cargo tab is not saved/displayed incorrectly. 

If you just created the item, you will have to check it to actually appears in game, wich seems to be intended.

If you save then reopen the project later, the item will sometimes. be unchecked, and if you check it, it will not appears in game. 

Sometimes, deleting an item from the list will not actually remove it and the item may still appears in game, the only way to remove it will be to remove the whole cargo template. 

It's a really weird bug that is pretty inconsisteznt, so sorry if this report isn't really clear but it's very hard to understand exactly how this bug is triggered.

**Comment by Mike7O** [comment]
info:

2022.1
editing custom cargo, when mod is created multiple lines are present in the **def.cargofile.sii**

`SiiNunit
{
@include "cargo/ct53.sui"
@include "cargo/ct53.sui"
@include "cargo/ct53.sui"
}
`

one have to manually edit and remove the duplicated lines
