### ISSUE TITLE
Project files (.ms2) not opening from within Windows File Explorer

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#146]
**Describe the bug**
If a user clicks on a ".ms2" project file to open a project to work on within MS2; MS2 opens but not with the project. MS2 opens with the default state.

**To Reproduce**
Try to open a .ms2 project file from within Windows File Explorer.

**Expected behavior**
MS2 project should open in MS2 when loaded.

**Screenshots**
See discord messages here for a screen shot (not really required):

https://discord.com/channels/611134812471820348/611135209525608488/924002162235834390

**Desktop (please complete the following information):**
v2021.03

**Additional context**
NOTE: Opening a project file from within MS2 (via File > Open MS2 project) still works as should do.

**Comment by pete-agreatguy** [comment]
Apparently has worked fine in the past in other versions.

**Comment by WerewolfCustoms** [comment]
> Apparently has worked fine in the past in other versions.

Very interesting! We used to have some file associations in Mods Studio 1 apps, but I don't think we ever had them in MS2.
In any case, I agree - we should have them, but I think I'll add them as a PRO feature. Good issue for the next release.
