### ISSUE TITLE
App reports "Export Successful" even if the destination file was occupied and was not overwritten

### ISSUE THREAD

**Issue by ve1oxby** [WerewolfCustoms/ModsStudio2IssueBoard#177]
**Describe the bug**

**To Reproduce**
1. Export your mod to .../mod/ folder
2. Launch the game with your mod (or just open this .scs file with something like 7zip to occupy the file)
3. Export your mod once again
4. The new file won't be written to the disk, because the file with the same name already exists and could not be overwritten
5. Although this, the user gets the "Export Successful" message. 

**Expected behavior**
The user should get an "Export Failed" message.

**Desktop (please complete the following information):**
 - Version v.2021.03

**Comment by pete-agreatguy** [comment]
I have been unsuccessful in reproducing this.

Including having the Mod Manager in game open with said mod moved over into the list (without clicking on confirm changes in mod manager so that the mod file was being accessed).

I double checked values changed and found that the successful export message was valid.

With both the game open and the mod opened within 7zip, the export fails with the expected result of the following error:

> -----------------------------------------------------------------------------
> Date : 11/02/2022 11:31:38
> 
> System.IO.IOException
> Message : The process cannot access the file 'C:\Users\Peter\Documents\Euro Truck Simulator 2\mod\ai_spawn_ratio_testing.scs' because it is being used by another process.
> StackTrace :    at System.IO.FileSystem.DeleteFile(String fullPath)
>    at System.IO.File.Delete(String path)
>    at ModsStudio2Library.Files.ScsMod.Scs.Pack(String inputDirectoryPath, String outputPath, CompressionLevel compressionLevel) in D:\Sources\ModsStudio2\ModsStudio2Library\Files\ScsMod\Scs.cs:line 105
>    at ModsStudio2Library.Models.ScsMod.ScsProject.Build(VariableList enviromentVariables) in D:\Sources\ModsStudio2\ModsStudio2Library\Models\ScsMod\ScsProject.cs:line 82
>    at ModsStudio2Core.Logic.Build.BuildProjectFile(String inputPath, String outputPath) in D:\Sources\ModsStudio2\ModsStudio2Core\Logic\Build.cs:line 70
>    at ModsStudio2Core.CLI.BuildOptionsHandler.ParseOptions(BuildOptions opts) in D:\Sources\ModsStudio2\ModsStudio2Core\CLI\BuildOptions.cs:line 47
>    at ModsStudio2Core.Program.<>c.<ProcessInput>b__3_2(BuildOptions opts) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 104
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at ModsStudio2Core.Program.ProcessInput(String[] args) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 95
>    at ModsStudio2Core.Program.Main(String[] args) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 76
> 

Did you do anything different to this?

**Comment by ve1oxby** [comment]
@pete-agreatguy yeah, I've just realised, before your comment, that this was not the case of false-success report, it is just confusion which was caused by the following UI design:

1. User successfully exported the mod.
2. User continues to do smth in this mod.
3. User press "Export Mod" button in left menu and _sees the previous "Export Successful" message_
This message was exactly what was confusing me. 

Sorry for the inconvinience. It would be good anyway to change this design in the future. 

p.s. I'm gonna be more careful in creating tickets here in the future, lol =).

**Comment by WerewolfCustoms** [comment]
We're getting a whole redesign for the export page in 2023.02:
All issues mentioned here should be resolved 👍 

![2023-09-05 22_32_09-ATS Mod Project  -  Mods Studio 2](https://github.com/WerewolfCustoms/ModsStudio2/assets/8348467/7e2af025-b166-4281-9d58-28dfe61271fa)
![2023-09-05 22_32_27-ATS Mod Project  -  Mods Studio 2](https://github.com/WerewolfCustoms/ModsStudio2/assets/8348467/c97fb9bd-55bf-4664-bf38-9249e1d3cc1f)
![2023-09-05 22_32_48-ATS Mod Project  -  Mods Studio 2](https://github.com/WerewolfCustoms/ModsStudio2/assets/8348467/e8e3a789-1567-410e-9e72-a24bcaedfb15)
![2023-09-05 22_33_26-ATS Mod Project  -  Mods Studio 2](https://github.com/WerewolfCustoms/ModsStudio2/assets/8348467/02e14483-4067-476d-ae17-0da9b8fe4882)
