### ISSUE TITLE
Add Default Mod Manager Description to advertise MS2 (read for details)

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#183]
**Is your feature request related to a problem? Please describe.**
I think it would be a good idea to have each mod created to include the phrase

> [blue]This mod was created using Mods Studio 2; the easy way to make SCS mods![normal]

Have this processed during export :) **Not** on the default Mod Manager description text page of MS2.

**Describe the solution you'd like**
During export, have the above code added to the top line of the mod manager description text (including a line break after).

Final output example:

![20220302131842_1](https://user-images.githubusercontent.com/74508456/156369310-0897c5e7-9363-4a59-9cdc-3438844d40c5.jpg)

**Additional context**
It will advertise Mods Studio 2 in a friendly manner and encourage new users to use the software.

**Comment by WerewolfCustoms** [comment]
This is a good idea, and I think we should do it.

However, to complicate things a little - I believe that our Pro users should have the option to disable this text.
I will take a look on how this could be implemented. 

I'll also take a look into the technicalities of the mod manifest template, and I'll answer your question, for reference sake. 👍

**Comment by pete-agreatguy** [comment]
Thank you for the feedback. I like the pro feature adaptation :)
