### ISSUE TITLE
Update AI vehicle spawn values to 2 decimal places

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#194]
AI Vehicle spawn ratio values need updating to 2 decimal places; including:

1) descriptions ...
2) ... and any validation

Files to edit:

AI Vehicle template files found in MS2Library > Models > ScsMod > Templates

1. AiTrafficSkin.cs
2. StandaloneTrailer.cs
3. TrafficTrailerSkin.cs
4. TrafficTruckSkin.cs

**Comment by WerewolfCustoms** [comment]
This might be completed, since our cargo updates have added 2 decimal places to all float numbers. :)
Have to test before closing issue. 👍

**Comment by pete-agreatguy** [comment]
In the pushed "backup" (feature\194 ....) I did prior to installing my system, I hadn't finished successfully adding a comment to one of the fields ... I can't remember which field off the top of my head ... nor does my git changes say what I had changed compared to the dev build :/ ... I'll have a look tomorrow when I can and get back to you 👍 as off to bed now.
