### ISSUE TITLE
Fuel Tanker Traffic Trailers ATS

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#196]
Is it possible to add the Fuel Tankers to traffic for ATS,like fuel tankers,im pretty sure the food tank we have is a different sort of tanker if im correct.

**Comment by WerewolfCustoms** [comment]
![ats_20221015_231643_00](https://user-images.githubusercontent.com/8348467/196007907-f2687036-acec-46a6-b2f9-26d4f2551bf2.png)

Here we go... the 43 footer and the big 53 footer are in.

**Comment by pete-agreatguy** [comment]
Has mdmodding returned or are you doing this yourself in blender?
