### ISSUE TITLE
Cant upload Ats mudflaps to steam workshop

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#198]
Tried to upload a set of mudflaps for the Lowboy,but kept getting 003 error
![Mudflaps Workshop Error](https://user-images.githubusercontent.com/72619819/161812993-b372e46d-ef7b-4976-9796-09fd041215f2.png)

**Comment by pete-agreatguy** [comment]
NascarBen seems to have found a way to upload these:

Message on discord link = https://discord.com/channels/611134812471820348/611134813021143041/969438271149076520

> Ok, I was able to get mud flaps working with the scs workshop uploader. It probably isn't the cleanest solution, but it's getting late and I don't want to keep pushing broken content to steam. In order to get the mod to upload I did the following.
> This is based on mod studio v2022.1 and scs workshop uploader 1.0.28
> 1. In your mod folder to upload to steam copy the universal/vehicle/trailer_owned/upgrade folder to universal/vehicle/trailer/upgrade.
> 2. Go into each Mudflap Internal Name folder under universal/vehicle/trailer_owned/upgrade/r_mudflap/ms2 and look for the d2 folder. Inside you'll find d2daa3bb25914d3d.mat.
> 3. Edit the path for texture[0] to "/vehicle/trailer_owned/upgrade/r_mudflap/ms2/[Mudflap Internal Name]/skin.tobj" where [Mudflap Internal Name] is the same as the internal name you used in mod studio 2.
> 4. Go into each Mudflap Internal Name folder under universal/vehicle/trailer/upgrade/r_mudflap/ms2 and look for the d2 folder. Inside you'll find d2daa3bb25914d3d.mat.
> 5. Edit the path for texture[0] to "/vehicle/trailer/upgrade/r_mudflap/ms2/[Mudflap Internal Name]/skin.tobj" where [Mudflap Internal Name] is the same as the internal name you used in mod studio 2.
> 6. Save all of the .mat file edits and then you can successfully upload your mud flap mods to steam.
> 7. I will also mention there are a lot of warnings still one for the manifest file not needing the description anymore and then a value for the mudflaps is unexpected and overriden "queue_bias : 1" I wasn't sure if removing that was also breaking my upload, but I didn't know what a correct value should be so I left the warnings. 
> I don't know the history of how this part of mod studio used to work, but it may be possible that the files only need to live in trailer and not trailer_owned, but it didn't appear to work for me when the files only lived in trailer_owned.

**Comment by pete-agreatguy** [comment]
Pauly, is this still happening after I released the patches for v2022.03?

**Comment by Paulycustomskins** [comment]
I've not tried it since,I thought someone said recently they still couldn't upload mudflaps,but not sure if it was before or after your patch

**Comment by WerewolfCustoms** [comment]
Tested with latest mudflaps (v.2024.02) and it works! 🎉🥳 

![image](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/6e50e018-e43a-433c-a07c-5fa9b5a352c6)
