### ISSUE TITLE
Daf XF euro6 xml is missing parts

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#208]
**Describe the bug**
The xml shipped with modstudio2 comes with accessories front mask and front grille. These only edit the top part of the relevant accessory 

**To Reproduce**
![ms2dafeuro6](https://user-images.githubusercontent.com/5055209/174668105-736d9533-7f62-45ee-bd44-649673f5b148.png)
results in this:
![ets2_20220620_202347_002](https://user-images.githubusercontent.com/5055209/174668440-b5f7be70-fffc-40b9-8bc7-d5b84171264b.png)

**Expected behavior**
As pictured
![ets2_20220620_202750_002](https://user-images.githubusercontent.com/5055209/174668758-22e4f29e-14a1-4cc4-9282-0128899f9436.png)

**Desktop (please complete the following information):**
 - Modstudio v.2022.1
 - ETS2 1.44 inc xf tuning pack

**Fix**
f_inlay_cab.paintable (and variants thereof) and f_intake_cab.paintable are only for the parts attached to the cab. The xml needs to have f_inlay_chs.paintable (and variants thereof) and f_intake_chs.paintable added as separate accessories to for the parts attached to the chassis.

I've attached a modified and tested XML file which adds the chassis parts for the mask and gril
[ETS2.daf.xf_euro6.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8943423/ETS2.daf.xf_euro6.xml.txt)

**Comment by pete-agreatguy** [comment]
Thank you for using the proper bug report system :)

Will look into it.

**Comment by pete-agreatguy** [comment]
Right so I know why this wasn't included initially.

When coding the xmls in the main app development, I only tend to select the in game dots that appear.

The def file for the DAF EU6's cab over-rides the chassis (as it takes the skin from the skin template). However, that said with the advanced skinning method being applied here, it would be correct to add the missing parts.

@taede Have you noticed similar issues on other trucks?

**Comment by pete-agreatguy** [comment]
I'll discuss with werewolf how we go about this in the future as normally we only implement what is seen in game 👍  i.e. the dots which allow for configuration.

**Comment by taede** [comment]
Findings so far:

**Daf XF105**
f_intake_chs.carpaint
Fixed XML: [ETS2.daf.xf.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986403/ETS2.daf.xf.xml.txt)




**Iveco Stralis Hiway**
sideskirt.shape1
sideskirt.shape2
Fixed XML: [ETS2.iveco.hiway.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986402/ETS2.iveco.hiway.xml.txt)

**Mercedes-Benz Actros 2014**
Centurion rear bumper has 3 variants (plain, painted and chrome)
The painted one is done correctly, however the plain one also has a painted part which does not get done. Not sure how to fix or if it is fixable

**Renault T (using ETS2 Renault T Update v1.3 from #ms2oficial_patches)**
s_stripe.paint should be s_strip.paint
Fixed XML: [ETS2.renault.t.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986401/ETS2.renault.t.xml.txt)

This includes all vanilla SCS trucks with advanced skinning xml's included in MS2, apart from Scanias and Volvos.
Still to check: Scanias and Volvos

**Comment by taede** [comment]
**Scania R 2009 & Streamline**
Same front mask issue as Daf XF xf_euro6, f_intake_chs.mg_carp is missing
[ETS2.scania.r.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986531/ETS2.scania.r.xml.txt)
[ETS2.scania.streamline.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986527/ETS2.scania.streamline.xml.txt)

**Scania R&S 2016**
Same front mask issue as Daf XF xf_euro6, the chassis part for the front mask, grille and ribs are missing
s_panel.painted is also misspelled as S_panel.painted (note the capital S). Same for s_panel.painted_f
[ETS2.scania.r_2016.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986532/ETS2.scania.r_2016.xml.txt)
[ETS2.scania.s_2016.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986534/ETS2.scania.s_2016.xml.txt)

**Volvo FH16 2012**
Same front mask issue as Daf XF xf_euro6, f_intake_chs.painted is missing
[ETS2.volvo.fh16_2012.xml.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/8986535/ETS2.volvo.fh16_2012.xml.txt)

This should be all trucks with advanced skins now, any not mentioned have no missing/incorrect parts that I could find.
All XML's have been tested

**Comment by pete-agreatguy** [comment]
Wow! Nice work!

You didn't need to do them all but we (@WerewolfCustoms and I) really appreciate this!

I'll post them up later on the discord. And code them into the next version when I can :)

**Comment by pete-agreatguy** [comment]
Fixed. See #212

**Comment by pete-agreatguy** [comment]
Linked with #215

**Comment by taede** [comment]
Nice, thank you.

Sidenote: the xmls also split the ribs on the scania next gens, and fixes the side panels. These are not listed in your change notes (the posted xmls are still correct though)

**Comment by pete-agreatguy** [comment]
I only tend to list important changes :)

**Comment by pete-agreatguy** [comment]
What do you mean by "split the ribs" sorry?

**Comment by taede** [comment]
The mask on the scania next gens consists of 3 parts. Mask, grille(inlay) and ribs

**Comment by pete-agreatguy** [comment]
Ah, understood. Those are the horizontal bars aren't they 👍 

In the 2022.02 release of ms2 I've re-grouped them all.
So there will be a group called Front Mask (Cabin) ... and to keep them tidy .... there will be another group Front Mask (Chassis) etc :)

**Comment by pete-agreatguy** [comment]
Like this:
![image](https://user-images.githubusercontent.com/74508456/175914542-4dd90eb4-da59-463e-87c3-a688f0a85a0b.png)

**Comment by pete-agreatguy** [comment]
@taede Worked out that SCS have added 2 variants of the centurium rear bumper which were not included initially with the Tuning DLC pack. They got added without announcement. They will be added now though! 😄

**Comment by taede** [comment]
Mum always told me not to pull threads. I seem to have given you lots to do.
