### ISSUE TITLE
Could we combine the Traffic Trailer and Standalone Trailer so we just have the 1 Traffic/Cargo market Trailer 

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#226]
Could we just combine these 2 traffic trailers so we just get 1 Traffic/Cargo market trailer,think it would be better just to have the one and so it doesnt confuse the people
![Screenshot_6](https://user-images.githubusercontent.com/72619819/178946368-5f0f95c6-efdd-4a12-9d97-789731f83ff4.png)
t

**Comment by pete-agreatguy** [comment]
I don't see a problem with renaming it :)

**Comment by TRGJrFan81** [comment]
The only problem is that the the 53 foot traffic trailer you can't skin the entire trailer like you can the standalone trailer. The standalone is much more detailed and easier.
