### ISSUE TITLE
Investigate 3D Previewer app not loading (not a clue why)

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#227]
**Describe the bug**
When attempting to load 3D Previewer app; either via the MS2 app or by the 3dp exe, the app does not load.

I have tried the following:

1. Clean installed Windows 10 Pro 64 bit
2. Rebooting after installing .net desktop runtime v5.0.17.
3. Disabling both antivirus (kaspersky) and Malwarebytes.
4. Copying over the exe from the archive version.
5. Running as admin.
6. Installing older versions of the exe from the following versions: v2021.03 ... v2021.02 ... v2021.01

**Expected behavior**
£D Previewer app should load.

**Screenshots**
n/a

**Desktop (please complete the following information):**
Latest, v2022.01

**Additional context**
OS is a fresh install. Fully updated.

**Comment by pete-agreatguy** [comment]
Discord conversation in dev channel which maybe of use.

m1key had a "UiErrorFile.txt" which maybe worth looking at.

https://discord.com/channels/611134812471820348/611170373773295616/998514562435383317

**Comment by pete-agreatguy** [comment]
Mine started randomly working after installing Visual Studio. Maybe something missing from the included .net files?

**Comment by pete-agreatguy** [comment]
Seems that Lucasi may have found the reason as to why this happening:

See discord dev message chat here:

https://discord.com/channels/611134812471820348/611170373773295616/1023579512866357289

**Comment by pete-agreatguy** [comment]
Installer now creates a "SkinPreviewExports" folder within Docs > Mods Studio 2 :) This will fix this issue for the installer.

**Comment by pete-agreatguy** [comment]
Current develop on remote has the code implemented:

Filesystem.cs (lines 14 through till 18):

`public static void CreateSkinPreviewDirectory()
        {
            if (!Directory.Exists(SkinPreviewExports))
                Directory.CreateDirectory(SkinPreviewExports);
        }`

**Comment by WerewolfCustoms** [comment]
@pete-agreatguy Did you forget to open the pull request? :)

**Comment by pete-agreatguy** [comment]
Nope. The current remote has the code already :) The issue can be closed :)

Unless there is a bug with the code already implemented? In the file mentioned.
