### ISSUE TITLE
Add an ability to search for specific accessories

### ISSUE THREAD

**Issue by Lonelytrucker2001** [WerewolfCustoms/ModsStudio2IssueBoard#231]
We need a function with which we can search for accessories in the accessories list faster and more specifically while creating a mod with Modstudio2. Some mods have a lot of accessories and it's very hard to find special parts.

I would like to get a Search-Function similar to that one at Discord. 
Where you can search for terms or filter out certain categories.

**Comment by pete-agreatguy** [comment]
+1

This gets my vote. Thank you for using the proper procedure :)

**Comment by WerewolfCustoms** [comment]
Bump! 🆙 Let's do this for next release!
