### ISSUE TITLE
Advanced skin templates can cross-contaminate in some conditions

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#233]
**Describe the bug**
When creating a mod which has 2 separate skins for the same truck/cab combination (for instance the DAF XG+ cab), the images and checkboxes for on the skins and accessories tab affect both skins.

**To Reproduce**
1. Create a new mod with a single advanced truck skin for a single cab and fill every field as you would normally.
2. Duplicate the template, and change the skin internal name and possibly the skin display name.
3. Check the remaining tabs in both skins, they should still be the same.
4. Change the image, or check different checkboxes in either the skins or accessories tab.
5. Check these tabs in both skins again. They should now both have the same changes applied to them. This only applies to these 2 tabs, other tabs retain their own settings

**Expected behavior**
When changing the image/checkbox in one advanced skin template, the other  one should not change

**Desktop (please complete the following information):**
 - Version 2022.1
 - Windows 10

**Additional context**
I have attached my .ms2 file (renamed to .txt, just rename it back to .ms2 to use it) with which I experienced the bug. Load into MS2 and replace the images and the bug should display itself
[Lesscher.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/9438621/Lesscher.txt)

Edit to add:
This issue only happens when using 'duplicate template' is used. Manually adding another advanced truck skin and filling it in circumvents it

**Comment by pete-agreatguy** [comment]
Thanks for using the proper report system :)

This is similar with the following issue:

https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues/92

I'll let werewolf answer this one in the future as this maybe intended behaviour at the moment? I'm not sure on this one.
