### ISSUE TITLE
Dropdown control item does not work properly with dark mode

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#236]
**Describe the bug**
With dark mode enabled, a particular dropdown control becomes very hard to read. It's only used in a handful of places, but ironically one of those places is the theme selector where you can enable dark mode. This only happens on the dropdown control where it is part of a table, like options or scs vehicle editor. Regular dropdown selections work as expected.

![MS2Dark3](https://user-images.githubusercontent.com/5055209/191774451-2bd6f912-9b97-4dd2-9dcd-535347db1f24.png)
![MS2Dark1](https://user-images.githubusercontent.com/5055209/191773404-fa61bbbc-c1c2-47c9-b1fe-027388945d43.png)

**To Reproduce**
1. Go to Settings -> Global Options
2. Set Theme (Pro) to Dark
3. Dropdowns selectors of this type will now be white text on white background.

**Expected behavior**
For the text to remain black like on the rest of the table, or even the background to become dark so that the text is legible

**Desktop (please complete the following information):**
 - Version: 2022.1
 - Windows 10 set to dark (setting colour to light in windows makes no difference for ms2)

**Comment by pete-agreatguy** [comment]
Known issue. Dark mode is not fully finished :) Ty for the report though.

**Comment by WerewolfCustoms** [comment]
Spent a couple of hours on this yesterday, and couldn't get it to work. 🤷‍♂️ I hate WPF 😅

[I've posted a job on freelancer.com to see if someone can do this for us for a reasonable price.](https://www.freelancer.com/projects/wpf/WPF-Style-the-PropertyGrid-from/details)

**Comment by pete-agreatguy** [comment]
Is this what you are looking for in regards to this werewolf?

https://stackoverflow.com/questions/36345082/how-to-change-the-backcolor-of-a-combobox-when-dropdownstyle-is-dropdownlist

**Comment by WerewolfCustoms** [comment]
No, the problem lies in the fact that this whole Property Grid is a third-party control and is not easily themed. (Well, it would be, but the authors want about 500$ for the feature.)

There's ways around it, but it's tedious. Thus, I would rather outsource this. It looks like I can get it done for $80, and I will probably pull the trigger and go for it.

**Comment by WerewolfCustoms** [comment]
600 lines of code later... :D

![Dark theme options work](https://user-images.githubusercontent.com/8348467/202873557-b3722a2e-144f-47f2-9aa3-153acd4c3d99.png)
![VariantEditorDark](https://user-images.githubusercontent.com/8348467/202873559-b59431f7-bfa5-427d-8d7f-6f3ae4cf73c8.png)
![Vehicle Editor Dark Theme](https://user-images.githubusercontent.com/8348467/202873560-a342b6f9-3356-41da-ab24-f01fe968eb73.png)

This will be closed with the cargo update. (Needed to fix this before adding more cargo editing capabilities)
