### ISSUE TITLE
SCS extractor and 3dViewer will not launch from the main program

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#241]
**Describe the bug**
SCS extractor and 3dViewer will not launch from within ms2 (this seems to be different from the general 3dviewer doesn't start issues). this was no problem as I could launch those manually. However I just tried to use the UV exporter, but when trying to load a pmg file (either through the load model button or drag-n-drop) nothing happens.

**Expected behavior**
Launch SCS-extractor or 3dviewer, or load model file in case of UV extractor

**Desktop (please complete the following information):**
Windows 10
.net SDK .5
Visual C++ redist 2015

**Additional context**
I have included logfiles generated by MS2 when I try any of these actions. Files contain a single instance each. The errors all seem nearly identical hence I reported this as a single issue.

[UiErrorFile-scsextractor.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/9678677/UiErrorFile-scsextractor.txt)
[UiErrorFile-3dpreviewer.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/9678678/UiErrorFile-3dpreviewer.txt)
The above 2 logfiles are generated when pressing the ms2 button for launching the respective app. The below logfile is generated when trying to load a .pmg file into UV exporter.
[UvExportErrorFile.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/9678698/UvExportErrorFile.txt)

**Comment by taede** [comment]
Update. The issue with 3d previewer was a case of pebkac. Some files did not get extracted and caused UV extractor to throw that error.

The issue with scs-extractor and 3d previewer persists though.

**Comment by WerewolfCustoms** [comment]
So, this is closely related to https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues/227 and will be fixed together.
