### ISSUE TITLE
Group Variable is not working for OldTrucks (works fine in NewTrucks)

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#242]
Noticed when you put a truck cab variant in a group it doesnt do that,i added a truck manually and tried to put the cabins into the different varients and it didnt do it....as you can see in the picture its the Variant group that doesnt seem to work. 
![Screenshot_22](https://user-images.githubusercontent.com/72619819/194238949-a3611d87-1992-4781-81ce-79862f5a5ac6.png)

**Comment by pete-agreatguy** [comment]
Pauly is referring to the cabin variants not grouping properly on the skin tab of a truck template:

![image](https://user-images.githubusercontent.com/74508456/194698985-5389223c-72bf-4937-ae0e-2977e295fcf1.png)

**Comment by Paulycustomskins** [comment]
Yeah on the gmc truck I wanted the 1978 cab variants in one group and the 1980 cab variants in another group and it didnt happen

**Comment by Mike7O** [comment]
**GROUP**  seems to only be working in **NewTrucks**
