### ISSUE TITLE
Compatibility with other plugins

### ISSUE THREAD

**Issue by Skerpiej** [WerewolfCustoms/ModsStudio2IssueBoard#243]
**Describe the bug**
When playing ETS2/ATS I make use of two programs your plugin and our VTC tracker which is build with the use of this plugin: https://github.com/RenCloud/scs-sdk-plugin I believe you use the same. However both programs don't work with the same .DLL file. So our tracker overwrites your .DLL file. However the cruise control buttons increase/cruise control / decrease no longer work, unless I put my hazard lights on.

**To Reproduce**
1. drag your ets2 telemetry in the plugin folder
2. boot game everything works fine
3. shut the game 
4. reboot the tracker receiving notification to update the plugin
5. streamdeck doesn't show the Cruise control speed unless hazard lights are on

**Expected behavior**
Showing the cruise control speed on the buttons. 

**Screenshots**
Everything is working fine with your .DLL
![unknown](https://user-images.githubusercontent.com/115171554/194353225-55e6a939-14e1-4498-907b-3ceb6d9fdc27.png)
Streamdeck no longer provides the cruise control steps unless hazard ligt
![unknown](https://user-images.githubusercontent.com/115171554/194353393-a0aa7a99-01c7-4e93-a92d-810ca4377dd1.png)

**Desktop (please complete the following information):**

**Additional context**
https://youtu.be/ZJuv3f4zSqg < this is a recording that shows exactly what happens during this entire process. 
![unknown](https://user-images.githubusercontent.com/115171554/194353393-a0aa7a99-01c7-4e93-a92d-810ca4377dd1.png)
![unknown](https://user-images.githubusercontent.com/115171554/194353850-d1f12ba2-a155-4e9d-b015-be004ac96815.png)

**Comment by pete-agreatguy** [comment]
Thank you for providing the report :) I'm sure if we can't fix this, that the other devs of the vtc plugin can 👍

**Comment by Skerpiej** [comment]
heya 
So ehm I've been talking about it with my vtc people (yeah lot of people 😆 
Annyways they mentioned something about renaming the .dll file. 
like now it's called scs-telemetry.dll however since more programs rely on it. 
it might be a easy thing for you guys to rename it into ms2-telemetry.dll for example.

If I check my plugins folder I have as per example:
dbus_telemetry.dll
TruckyTelemetry.dll

and more like that

**Comment by WerewolfCustoms** [comment]
Our DLL file is indeed renamed now, as @Skerpiej suggested, to `ms2-telemetry.dll`
Also, the in-memory filename was changed to `Local\MS2Telemetry` to avoid further conflicts.
Other optimizations, upgrades and bugfixes to the dll file were also made. :)
