### ISSUE TITLE
Container chassis and mudflaps  

### ISSUE THREAD

**Issue by King-Leo-1966** [WerewolfCustoms/ModsStudio2IssueBoard#247]
It would be nice if the container chassis including sideskirts and mudflaps could also be customised. SCS Standard as well as Krone DLC and Schwarzmüller DLC.
Please also check whether a mudflap personalisation option can be added for all models of the trailers mentioned.

**Comment by pete-agreatguy** [comment]
So after testing the Krone Boxliner; afraid it is not able to take on a player skin as you would like it to be. You could put in a request for it to be on the SCS forums.

Which Schwarzmuller trailer did you mean?

**Comment by King-Leo-1966** [comment]
But then how come there are packages with mudflaps for all trailers?
I'm not sure right now whether the Schwarzmüller DLC also has a container trailer. I'll have to check.

**Comment by pete-agreatguy** [comment]
Schwarzmuller doesn't have a container trailer. Not sure if one is planned in the future or not either.

With regards to trailers with mud flaps; not all of them do have these. MDmodding is the who completed those and sadly he is currently MIA (missing in action). We are not sure when or if he will return to work with us again on such projects. Remember, we developers volunteer our time on MS2 :)

**Comment by King-Leo-1966** [comment]
Too bad, but thanks for trying.
