### ISSUE TITLE
ETS2 truck windscreen decal visual errors in the game

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#253]
**Describe the bug**
Project-template doesn't create individual filepaths when creating for multiple trucks

**To Reproduce**
1. create a mod for multiple trucks or multiple mods for individual trucks
2. add to game
3. check individual trucks created model
4. they use the same model from last created truck...and if using multiple mods...the one with highest priority will be used

**Expected behavior**
to see the windowdecal work just fine.

**Screenshots**
**![github](https://user-images.githubusercontent.com/66170614/197586106-ce03b34c-7fe3-4525-bc5b-a06668635b5a.png)**

**Desktop (please complete the following information):**
 - Version 2022.01

**Additional context**
A fixed Project-template available in the discord
https://discord.com/channels/611134812471820348/611170373773295616/1034149520113668166

**Comment by pete-agreatguy** [comment]
Cheers chuck. Will get the code and that done now.

**Comment by pete-agreatguy** [comment]
Completed and pushed to github.
