### ISSUE TITLE
Add traffic truck skin mod template

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#26]
Research and implement the option to skin traffic trucks.
This could be the "free" part of the feature.

It would be even more awesome if they could be matched with trailers.
Maybe have this as a pro feature?

**Comment by RemiJL** [comment]
It would be nice if I could create my own matching tractor & trailer fleet and see them on the road sometimes!  JazzyCat has them for different companies but I don't know what program he uses to create them all!...  This would be a very interesting feature to have in the MS2.  Thanks for all the hard work you invested into this software, I love it!

**Comment by WerewolfCustoms** [comment]
Thanks for pointing me in the direction of JazzyCat's mod. I'll take a look how it's made and try to recreate it for the June release. Also, welcome to our GitHub board! :)

**Comment by RemiJL** [comment]
Thank you so much for your interest in this cool feature!
Good luck!
