### ISSUE TITLE
Different ETA display with hh:mm and distance to waypoint in Trip info please! 

### ISSUE THREAD

**Issue by mex3456** [WerewolfCustoms/ModsStudio2IssueBoard#265]
Hello! Is it possible to change the ETA in the Trip info to hh:mm if there are >60 mins? And show the distance to the next navigation waypoint and not the destination? Please make it happen!  That would be awesome! 
Can't add a lable :(

**Comment by WerewolfCustoms** [comment]
**Update hours display:**
- [ ] Trip info
- [ ] Rest info

**Trip info action:**
- [ ] Add distance to waypoint (PRO)
