### ISSUE TITLE
ATS / ETS2 Add DLC trucks to DLC Dependencies

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#269]
Need to add All  DLC trucks to the DLC Dependencies section
![Screenshot_26](https://user-images.githubusercontent.com/72619819/204760199-f54a79af-fba4-4894-8c85-1224228225c2.png)

**Comment by WerewolfCustoms** [comment]
Done! :)
