### ISSUE TITLE
Reduce the amount of templates for mudflaps

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#272]
We need to remove the amount of templates in the mudflaps,some are just the same as the next one,you can make 1 mudflap that fits all,so we don't need to have 3 templates the same.

**Comment by pete-agreatguy** [comment]
Hi Pauly my friend :)

Which mud flaps are you referring to?

And specifically which can be merged into one? Please provide all in a list.

Thank you :)

**Comment by pete-agreatguy** [comment]
For each truck mud flap ...

(a) Check each truck mud flap template and see which match.
(b) If they match, check to see if there are differences in accessory placement on the truck model.

If no changes to placement, then (c) remove duplicate code required:

- [ ] Freightliner Cascadia 2019 Base
- [ ] Freightliner Cascadia 2019 Aero X
- [ ] Freightliner Cascadia 2020 Aero X
- [ ] International 9900i Exclusive
- [ ] International 9900i International
- [ ] International 9900i Standard
- [ ] International Lonestar Standard
- [ ] International Lonestar International
- [ ] International LT Standard
- [ ] International LT Aero
- [ ] International Chrome
- [ ] Kenworth T680 Standard
- [ ] Kenworth T680 Mid
- [ ] Kenworth T680 Exclusive
- [ ] Kenworth W900 Standard
- [ ] Kenworth W900 Long Chassis
- [ ] Kenworth W900 Long Chassis, short cab
- [ ] Kenworth W900 Short Chassis
- [ ] Mack Anthem Exclusive
- [ ] Mack Anthem Standard
- [ ] Peterbilt 389
- [ ] Peterbilt 579 Standard
- [ ] Peterbilt 579 Mid
- [ ] Peterbilt 579 Exclusive
- [ ] Volvo VNL Standard
- [ ] Volvo VNL Advanced
- [ ] Volvo VNL Long mud flaps
- [ ] Western Star 49x

**Comment by pete-agreatguy** [comment]
**RESULTS:**

**1. Freightliner Cascadia**

a) Slight Difference between the AERO X 2019 and 2019 Base:
![Freightliner Cascadia 2019 Base vs Aero X](https://user-images.githubusercontent.com/74508456/218502790-a19e1120-6fa5-48cf-9b20-134ccb648dab.png)

b) Massive difference with the AERO X 2020:
![Freightliner Cascadia 2019 vs 2020](https://user-images.githubusercontent.com/74508456/218502984-6a129771-aa66-4dd7-b3c5-e05d0b477354.png)

**2. International 9900i (Eagle):**

Big differences between all three templates:
![International 9900i Eagle](https://user-images.githubusercontent.com/74508456/218503363-0ff76d07-0dfa-4060-ba68-94921ece677f.png)

**3. International Lone Star** 

Slight difference (larger corners). We should probably keep these separate:
![International LoneStar](https://user-images.githubusercontent.com/74508456/218503575-c67c1392-2c55-40f2-9508-d83f64077702.png)

**4. International LT**

Slight difference (in the corners). We should probably keep these separate:
![International LT](https://user-images.githubusercontent.com/74508456/218503895-3e47309b-742d-4579-8601-0eb4a1fe29ca.png)

**5. Kenworth T680 (merge)****

There are no differences. **These can be merged!**
![Kenworth T680](https://user-images.githubusercontent.com/74508456/218504207-0e19db1c-d1c7-4cef-a804-b380e87e129b.png)

**6. Kenworth W900**

There are large differences between the templates here. We should keep these separate:
![Kenworth W900](https://user-images.githubusercontent.com/74508456/218504461-0e888afc-5f7c-4c11-994e-500d9e4129ef.png)

**7. Mack Anthem**

The templates are very different. We should keep these separate:
![Mack Anthem](https://user-images.githubusercontent.com/74508456/218504695-6dc69b40-31e3-44d2-84aa-7225af57eebb.png)

**8. Peterbilt 579 (possible merge???)**

There are minor differences between these templates. See details below.

We could merge these but if doing so, we should only include the smallest template.
What do you think?

a) v3 (large) vs v1 (small) - MINOR DIFFERENCE:
![Peterbilt 579 v3 Large vs v1 Small](https://user-images.githubusercontent.com/74508456/218505348-40aa6aae-acfd-446a-b57e-38ae2a6a60f3.png)

b) v2 (medium) vs v1 (small) - Hardly any difference (need to zoom in):
![Peterbilt 579 v2 Medium vs v1 Small](https://user-images.githubusercontent.com/74508456/218505396-f574fcdc-e7db-4bac-a6f7-0b183aa08c90.png)

c) v3 (large) vs v2 (medium) - Again, hardly noticeable):
![Peterbilt 579 v3 Large vs v2 Medium](https://user-images.githubusercontent.com/74508456/218505783-54ef24b8-dbaf-4a60-8616-218603275172.png)

9. Volvo VNL

Large differences. We should keep these separate:
![Volvo VNL](https://user-images.githubusercontent.com/74508456/218506403-3528654c-44e8-439b-8a7d-a783705d653a.png)

**Comment by Paulycustomskins** [comment]
Yes I had checked the w900 ones and they did show differences,I think md made more work for himself with that one,I think if they can be merged then I say merge them,it just cuts down on confusing people

**Comment by pete-agreatguy** [comment]
389 only has one template :)

- [ ] Re-code Kenworth T680
- [ ] Re-code Peterbilt 579
- [ ] Rename model files accordingly
