### ISSUE TITLE
Add support for Suspension options (see image included)

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#284]
**Is your feature request related to a problem? Please describe.**
You cannot raise or lower suspension currently. 

**Describe the solution you'd like**
Add support for the following suspension options:

![image](https://user-images.githubusercontent.com/74508456/209339063-d1728229-94d6-4728-8079-49987fa20458.png)

**Additional context**
Stream deck. Added on behalf of MrChris#3313, discord.

**Comment by WerewolfCustoms** [comment]
I think this was a request for foreign keys :D In any case, we can fix both. :D

**Comment by pete-agreatguy** [comment]
Use icons found here in issue #201
