### ISSUE TITLE
Streamdeck - Speedlimit missing digits

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#285]
**Describe the bug**
Driving through some mapareas speedlimit is 1OO, which isn't displayed properly on the streamdeck.

**To Reproduce**
1. Always at these 1OOkm/h roads

**Expected behavior**
Display **1OO** instead of **1O** 😎

**Screenshots**
![streamdeck_speedlimit_1OO](https://user-images.githubusercontent.com/66170614/209468204-b1549968-20fb-49b4-9455-df4ad0ef4058.jpg)

**Desktop (please complete the following information):**
 - Version 3.0

**Comment by pete-agreatguy** [comment]
It should say speeding if going over 56mph no? 100 kmh = 62mph lol
