### ISSUE TITLE
Fixes ETS2 TruckLightbox scs_volvo_fh12_paint issues

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#294]
**Describe the bug**
two forgotten LOOKS still included in the modelfile 
causing issues IF one wish to upload to steam workshop.

**To Reproduce**
1. well just create a mod and it will be there
2. works perfectly fine as is, but some people wish to share it on steam....

**Expected behavior**
No errors in-game - ONLY if choosen to be uploaded to workshop
LOOKS deleted in projectfolder and exported mod doesn't give 
any errors in-game or when uploaded to Workshop (screenshots)

**Screenshots**
![ets2_20230104_012450_00](https://user-images.githubusercontent.com/66170614/210464518-70ad3696-bda8-4f34-91ee-0ec19e168fb3.jpg)

![ets2_20230104_012507_00](https://user-images.githubusercontent.com/66170614/210464519-c255d4c0-2625-42e2-8892-d22aabf9403e.jpg)

![ets2_20230104_012516_00](https://user-images.githubusercontent.com/66170614/210464522-76c4a664-908e-454b-a561-3f637654081a.jpg)

**Desktop (please complete the following information):**
 - Version [e.g. 2022.03]

**Additional context**
Deleted those LOOKS and 
the automatfolders; 14,32 & ad are obsolete - deleted aswell - no errors shown with additional testing. 😎

**Comment by pete-agreatguy** [comment]
Where are said edited automat files?

**Comment by Mike7O** [comment]
there aren't any ....removed aswell ...
 — 2023-01-04 02:01  - my post on discord regarding this included the projectfile

**Comment by pete-agreatguy** [comment]
For reference ... Discord messages onwards from the following:

https://discord.com/channels/611134812471820348/611170373773295616/1059986632176050237
