### ISSUE TITLE
Improve uninstaller header values in programs and features

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#295]
Use the following as a ref: https://learn.microsoft.com/en-gb/windows/win32/msi/uninstall-registry-key?redirectedfrom=MSDN

Currently the uninstaller looks like this which isn't really professional of us:
![image](https://user-images.githubusercontent.com/74508456/210537695-695733eb-2725-45c5-ac7e-29701428626b.png)

Adding extra heading information by adding registry keys will improve the professionalism of the installer :)

Use the main registry key:

\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Mods Studio 2

The following header values do **not** need to be created or uninstalled (deleted) as they are done so automatically:

DisplayName
UninstallString

Add the following:

- [x] DisplayVersion = 2022.03
- [x] VersionMajor = 2022
- [x] VersionMinor = 03
- [x] Contact = https://discord.gg/q26AuW7
- [x] Comments = Create mods quick and easy! All the tedious manual labour is done by Mods Studio; so you can spend time on what matters, designing the best looking liveries!
- [x] DisplayIcon = #InstallDir#\ms2.ico
- [x] HelpLink = https://www.mods.studio/tutorials
- [x] InstallDate = #Day#.#Month#.#Year#
- [x] InstallLocation = #InstallDir#
- [x] Publisher = Roadside Studio
- [x] URLInfoAbout = https://www.mods.studio/
- [x] Size =

**Comment by pete-agreatguy** [comment]
@WerewolfCustoms , are you alright with the information as in the above post? Thank you :)

**Comment by pete-agreatguy** [comment]
![image](https://user-images.githubusercontent.com/74508456/210566589-e4dfde4c-ea74-457e-8fc7-e225ee3ad33b.png)

![image](https://user-images.githubusercontent.com/74508456/210566732-0fb2b2e5-9159-418c-9551-d2af1556e526.png)

**Comment by WerewolfCustoms** [comment]
> @WerewolfCustoms , are you alright with the information as in the above post? Thank you :)

Looks great!
