### ISSUE TITLE
ATS: AI VAN and BUS

### ISSUE THREAD

**Issue by fosloks1** [WerewolfCustoms/ModsStudio2IssueBoard#297]
it would be interesting the possibility of van and bus in ats traffic, maybe a pickup truck too, if possible.

**Comment by Mike7O** [comment]
the projects in ETS2 can be used in ATS   .... as they are standalone models

**Comment by WerewolfCustoms** [comment]
![ats_20230212_194451_00](https://user-images.githubusercontent.com/8348467/227039620-952c43f9-dc6c-47d5-b4bd-ea401fc14836.png)
![ats_20230212_194620_00](https://user-images.githubusercontent.com/8348467/227039696-5b2d4336-3161-440f-9ad6-4216e79c3668.png)
