### ISSUE TITLE
Request: FAQ/Common Issues section for streamdeck plugin

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#299]
I've written out a small FAQ section for the Streamdeck plugin:

```
Streamdeck FAQ:
Q: The Streamdeck app does show the modstudio2 buttons after I've installed the streamDeckPlugin in step 3:
A: Sometimes the app needs to be restarted after installation before the buttons are available to assign to a profile. Alternatively, you can reboot your PC after step 3.

Q: My streamdeck shows and updates icons, but pressing buttons doesn't do anything or doesn't match the button:
A: The keys in the game should match the key set in the streamdeck app. Changing one does not change the other automatically.
A: Only use the normal letter/number keys, avoid special keys like pgup/pgdown etc. Avoid using keys that are not marked green in the below image.
	[keyboard.png]
A: Use lowercase letters for preference. Upper case does not always work properly, this is under investigation.
	[ets2.png][streamap.png]

Q: Streamdeck buttons work, but the icons do not update:
A: Check "Documents\Euro Truck Simulator 2\game.log.txt", it should contain a line something like "00:00:04.434 : loading 'scs-telemetry' 'C:/Program Files (x86)/Steam/steamapps/common/Euro Truck Simulator 2/bin/win_x64/plugins/scs-telemetry.dll' ". Using ctrl+f and searching for "dll" will help you find the line quick.
	If no such line is present, the plugin is not loading. Make sure the plugin is installed exactly as mentioned in step 2 of installation.
A: Other plugins (trucky, simdashub and similar) may interfere. Remove the relevant plugins. This issue is under investigation.
```

Images attached. Written to the best of my knowledge, but please doublecheck especially whether something is actually 'under investigation'

![ets2](https://user-images.githubusercontent.com/5055209/211368924-94316664-d97b-49af-ba6d-a2b5e3d1ad21.png)

![keyboard](https://user-images.githubusercontent.com/5055209/211371892-c9438c17-148e-4299-9e91-3266a328f70c.png)

![streamap](https://user-images.githubusercontent.com/5055209/211368932-7e4bf06f-16da-4fed-abc8-cabbae35d96c.png)

**Comment by pete-agreatguy** [comment]
Completed.

@WerewolfCustoms 

Login to the web site and check the following unpublished pages:

![image](https://user-images.githubusercontent.com/74508456/217244561-0e035f82-04f4-4f49-8908-908e840980ce.png)

When happy, publish them :)

Only edit to the Stream Deck page was updating the Support section with a link to the new FAQ page :)

**Comment by pete-agreatguy** [comment]
thank you Tadea for completing this.

**Comment by WerewolfCustoms** [comment]
Published!
Great work @pete-agreatguy and @taede
