### ISSUE TITLE
Could we skin the Escort Vehicles

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#314]
I know there used to be a mod out a while back that let you skin the escort vans for the Heavy Haulage,could it be possible for MS2 to do the same thing,think it would be a good addition if it can be done.

**Comment by WerewolfCustoms** [comment]
Yes, it was on my personal wishlist for a while now.

**Comment by WerewolfCustoms** [comment]
Closing this issue since we already have it for this feature 👍 

https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues/43
