### ISSUE TITLE
New mudflaps template for Kenworth W900

### ISSUE THREAD

**Issue by GearJammer-2** [WerewolfCustoms/ModsStudio2IssueBoard#320]
**Is your feature request related to a problem? Please describe.**
The current mudflaps template for the Kenworth W900 doesn't create a functional mudflaps mod for the truck using Mods Studio 2.
**Describe the solution you'd like**
An updated or new template for the Kenworth W900 truck mudflaps.
**Describe alternatives you've considered**

**Additional context**

**Comment by pete-agreatguy** [comment]
will be addressed via #324
