### ISSUE TITLE
ATS Kenworth W900 Truck Mudflaps need re-doing

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#324]
The ATS Kenworth W900 Truck mud flaps don't appear where they should and ergo need re-doing since SCS Software re-did the model.

- [x] Remove old code and files not required for new v2023.1 release
- [ ] Re-do code and model files for new release

**Comment by Paulycustomskins** [comment]
did these get added to latest release
