### ISSUE TITLE
Mod Studio 2 - v2023.01. - no mudflaps

### ISSUE THREAD

**Issue by SchmidtFG** [WerewolfCustoms/ModsStudio2IssueBoard#332]
**Describe the bug**
After installing MS2 v2023.01. \vehicle\trailer\upgrade\mudflap\ms2\' path is missing completely from \scs_trailer\  folder.

**To Reproduce**
1. install v2023.01.
2. create and save a mudflap template
3. press export

**Expected behavior**
Successful export.

**Screenshots**
---------

**Desktop (please complete the following information):**
 - Version 2023.01.

**Additional context**
---------

**Comment by pete-agreatguy** [comment]
Devs ...

For details of troubleshooting steps taken see onwards from the following forum post:

https://forum.scssoft.com/viewtopic.php?p=1810614#p1810614

Schmidt commented ...

> Uninstalled 2023.01. and installed 2022.01., the libraries appear in order. All of them.
> Also have a backup of this freighter mudflaps mod, import-save-export works perfectly, no error logs.
> For some reason the new 2023.01. doesn't contain mudflaps directory for me.

**Comment by SchmidtFG** [comment]
Hello Pete,

Thanks for the heads up!
I look forward to testing the new version.

Regards
SchmidtFG

pete-agreatguy ***@***.***> ezt írta (időpont: 2023. júl.
25., Ke 15:45):
