### ISSUE TITLE
Accessory selection improvements

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#340]
**Is your feature request related to a problem? Please describe.**
In the accessories tab (Advanced/Simple truck skin, Trailer skin) the selector for the accessories is a fixed size. It would be nice if this was expandable in some way as some XML's have more items in a single group than the  selector can show in one go.
The main 'images' tab would also benefit from this, but only if there are a lot of cabins/bodies to select.
When adding a full size 4kx4k image to an accessory, there is empty space which could be used.

**Describe the solution you'd like**
* Allow resizing of the selector, or the 'image' unit, moving the 'delete image' button down if necessary

**Describe alternatives you've considered**
* Simply extend the selector be be as tall as the section as if it had a 4kx4k preview image. (see attached picture, top 2 images). Drawback is 4x4 image accessories take up a lot more screensize)
* Keep current minimum size, but extend the selector when image is taller than the selector. Drawback is most accessories take a 4x4  image, so doesn't help all that often.

**Additional context**
![accessories](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/5055209/179e9139-a0f9-444e-8b27-c6857aec1ed7)

**Comment by WerewolfCustoms** [comment]
Accessories list now has a bit more height available, and also added a filter.
![image](https://github.com/user-attachments/assets/3ecfdc11-51a7-48ab-8fd8-b603cb271d91)

**Comment by WerewolfCustoms** [comment]
I have tried to make it resizable, but it ended up breaking the layout since it's 3 layers of controls there... ending up with 3 scrollbars side-by-side 😅  (List of accessories itself, List of images, and the tab as well.)
