### ISSUE TITLE
freightliner sunshild

### ISSUE THREAD

**Issue by dgoldhaber** [WerewolfCustoms/ModsStudio2IssueBoard#347]
the sunshild in the AI truck  are missing
According to the lights that are there it looks like it should be the sun shield but in reality it is missing and it greatly hinders the game experience.
And if it is also possible to add a version with a plastic grill, it will add a lot to the traffic mods' realism

**Comment by Mike7O** [comment]
https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues/268
