### ISSUE TITLE
Make a documentation page explaining Alternate UV set

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#35]
A lot of our users don't understand the point of Alternate UV set option.
Write a documentation on our website that explains it.

Add the link to all applicable templates.

**Comment by pete-agreatguy** [comment]
Is this issue completed with the following done?

https://www.mods.studio/docs/references/alternate-uv-set-scs

**Comment by pete-agreatguy** [comment]
This is already completed. Ergo, closing issue.
