### ISSUE TITLE
Add a tandem truck and trailer to traffic

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#356]
Could it be possible to add a tandem truck & trailer to traffic for both games,think it would go down well with the community,if it can be done

**Comment by WerewolfCustoms** [comment]
🎉 🥳 
![Artboard 1](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/4d9dfff8-a3c3-427f-a142-0e72bd20d166)
