### ISSUE TITLE
Error log preview on Export Failed page

### ISSUE THREAD

**Issue by GuiVer010** [WerewolfCustoms/ModsStudio2IssueBoard#371]
Following a discussion, I was thinking that, in addition to the "Show error log" button already existing (without replacing it), there could be an embedded text box inside the Export Failed page that would allow to read the log without the need for an additional click.
That would allow users to preview the error cause much more explicitly, as well as save some time for people trying to help.

**Comment by WerewolfCustoms** [comment]
![2023-09-04 21_06_41-ATS Mod Project  -  Mods Studio 2](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/51b72acf-9d8e-43fb-8ba7-6b7357a89009)

Coming soon :)
