### ISSUE TITLE
Could we add the new W900 to traffic

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#373]
Could the new W900 be added to traffic because the old one looks bad with a skin on it 
![Screenshot 2023-08-11 120855](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/8d34356e-f0cd-451a-8131-5f2417ff19f8)

**Comment by AdamLabrosse** [comment]
#516
