### ISSUE TITLE
Add more standalone trailers for ATS

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#383]
Could we add more standalone trailers for ATS

Livestock ( a paintable one would be very popular in ats )
Fuel tanker ( scs tankers are shocking to skin )

Edit (to have them in the changelog):
- [x] #432
- [x] #433
- [x] #434
- [x] #435
- [x] #436
- [x] #437
- [x] #439
- [x] #438
- [x] #440
- [x] #441

**Comment by AdamLabrosse** [comment]
Here is work in progress on Livestock belly StandaloneTrailer option. Red parts are elements that will be paintable. Do you agree with this design?

![livestock_belly_front](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/124315137/b0d521ee-6b8f-4aad-8276-d2b6edf64285)
![livestock_belly_rear](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/124315137/134e57b8-9fed-4962-8657-a7543139fea9)

**Comment by Paulycustomskins** [comment]
That looks great to me Adam

**Comment by AdamLabrosse** [comment]
Could you explain in detail what you find shocking to skin in the SCS fuel tanker so that I wouldn't reproduce the same errors in the UV-mapping of the StandaloneTrailer fuel tanker?

**Comment by Paulycustomskins** [comment]
It's the chrome effect on the skins,they look like a glass effect on a any skin we do on them

**Comment by AdamLabrosse** [comment]
Ok, I see. It will not be difficult to fix.

**Comment by WerewolfCustoms** [comment]
- [ ] New ATS Standalone trailers: Flatbed 28", 45", 53"
- [ ] New ATS Standalone trailer: Dropdeck 48", 53"
- [ ] New ATS Standalone trailer: Dryvan 28", 53"
- [ ] New ATS Standalone trailer: Insulated 28", 53"
- [ ] New ATS Standalone trailer: Reefer 28", 53"
- [ ] New ATS Standalone trailer: Chipvan
- [ ] New ATS Standalone trailer: Fueltank 43", 53"
- [ ] New ATS Standalone trailer: Grainhopper 40", 50"
- [ ] New ATS Standalone trailer: Livestock Belly

**Comment by Paulycustomskins** [comment]
Looking great guys
