### ISSUE TITLE
File association warning box doesn't display correctly in dark theme mode

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#387]
**Describe the bug**
Warning box in dark theme mode isn't displaying correctly. See screen shot below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set Dark Theme (reboot ms2)
2. In File Associations click on associate .ms2 and look at the warning box that appears.

**Expected behaviour**
Should display in dark theme mode rather what it is doing (see screen shot below).

**Screenshots**
![image](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/74508456/f478fbbe-d5dc-4dca-acb0-8902ce653c6f)

**Desktop (please complete the following information):**
v2023.02

**Additional context**
n/a

**Comment by WerewolfCustoms** [comment]
Reverted to Windows message boxes.

![image](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/0cfc2c08-7cab-4011-a2f8-56740e0c0b2d)

![image](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/8ec9def3-2c55-4ef2-af2c-40790911d548)
