### ISSUE TITLE
Painted Garages

### ISSUE THREAD

**Issue by Paulycustomskins** [WerewolfCustoms/ModsStudio2IssueBoard#388]
So we know we can get other peoples mods for painted garages,but im wondering would it be something that could be done with mod studio.......especially how well adam has produced some brilliant additions.....think painted large garages for both games would be a brilliant addition if it can be done.

**Comment by Paulycustomskins** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1963687850

**Comment by Paulycustomskins** [comment]
yes thats it pete......think the painted garage would be brilliant

**Comment by Paulycustomskins** [comment]
Think it needs to be for both games

**Comment by AdamLabrosse** [comment]
I took a look into modding garage and it seems it could be possible to create skinnable garage. As garage model aren't supposed to be skinned. Garage models must be replaced to do so. But some details need to be clarified.

Is the purpose of this feature to create a garage skin for your owned garages or for all garages in the game?
It seems that SCS doesn't make different models and definitions for default garage and owned garage. So modifying garage model will affect every garage of the same type (tiny, small or large) in the game. So it would be difficult to make a skin for only owned garages. I'm not sure but garages that can be bought are always small garages. If true, only skinning large garage would make this difference possible.

For ETS2, there are two types of garages, default and scandinavian. Which one need to be skinned? Both?

What should be skinned? Walls? Interiors? Adding a panel on the roof for company name and logo? Modifying textures or inserting a layer to paint the default texture?

**Comment by Paulycustomskins** [comment]
So the mod we have used changes the large garages in ATS to the same as in ets2,mainly I always skinned the outside because the inside would never come out very good,definitely a company board on the roof

**Comment by AdamLabrosse** [comment]
The Large garage with ramps looks beautiful and can be an option of garage design if the modder agrees to share it with MS2. Firstly, we can just make default garage designs skinnable. it will be a good start and an interesting project.

My idea is not modifying textures but introducing paintjob into the models to let users easily customize the look of their garages. That's the reason of my questions. I want to know which parts of the garages need to be paint. Obviously the exterior walls is the first thing wher adding paintjob.

I think I should try to make a custom garage when I would have done the job with ATS traffic.

**Comment by Paulycustomskins** [comment]
I would normally be able to paint the walls and the garage doors,would also be able to change the garage fencing aswell as the wall

**Comment by AdamLabrosse** [comment]
The fence is part of the model. So yes, it is possible to change the fence.

**Comment by Paulycustomskins** [comment]
Well as you are aware ive been in contact with Jab Modding who makes a very good custom garage for ATS....he is also happy to work with us at mod studio,he has joined the discord last night,i think we should work hard to include this if we can of course.
![Screenshot 2023-11-13 100333](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/d260895f-9862-4844-b363-5885cb8a7aa3)
![ats_20231113_092450_00](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/64c4c88d-b75d-42d6-a975-8def1596cf17)
![ats_20231113_093422_00](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/f5cdc734-8e4d-4a63-8924-cf465579f10b)
![ats_20231113_093429_00](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/a0574f77-81e2-456e-ab20-bf5e15e0c20f)
![ats_20231113_113207_00](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/555f8955-431f-496e-aa67-8b9688659bbb)
you can paint the buildings,fences,you can have different trailers spawn in the yard,
[
![Screenshot 2023-11-14 083122](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/72619819/d9c97872-0125-4c64-89a2-e41bd77163e7)
](url)
he seems keen to work with us as he does with other people.......i think having this garage mod in ATS and being used on Modstudio would make it very popular.

**Comment by Paulycustomskins** [comment]
https://www.facebook.com/JabModshop this is his facebook page where you can download the mod.

**Comment by WerewolfCustoms** [comment]
I'm building a MS2 prototype for Jab's garage. 👍

**Comment by Paulycustomskins** [comment]
Oooo nice one mate

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WerewolfCustoms** [comment]
![Jab's Garage Template Teaser](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/8348467/88452d08-bb4d-495a-9567-ec653505a7ff)

Yup, it'll work. 👍

**Comment by Paulycustomskins** [comment]
That's great news mate

**Comment by Paulycustomskins** [comment]
This is fantastic news

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WerewolfCustoms** [comment]
Closed the issue for now. We can open a new one when we decide to add more garages.
