### ISSUE TITLE
New version available window visual issues

### ISSUE THREAD

**Issue by taede** [WerewolfCustoms/ModsStudio2IssueBoard#443]
<img width="313" alt="2024_03_17_10_12_43_New_version_available" src="https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/assets/5055209/7dd1f60b-e979-4cbb-b971-2c0bc36334bc">

**Describe the bug**
When in dark mode, the window pictured above has room for improvement:
* The changelog is black text on white background
* The 'Download (installer)' button highlight colour is the same blue as in light mode, but with white text making it hard to read

Other bugs:
* Download installer actually downloads zipfile
* Download zipfile does nothing
* Skip version does not remember you wanted to skip
(source for the last 3: Werewolf)

**To Reproduce**
Install outdated ms2, activate Pro, set to dark mode. restart ms2. The window will pop up.

**Expected behavior**
* White text on grey background
* Change blue colour on highlighted button

**Desktop (please complete the following information):**
 - Version 2023.3

**Comment by WerewolfCustoms** [comment]
![image](https://github.com/user-attachments/assets/57aafee7-fe3c-41b4-9fad-d0a30226989e)

**Comment by WerewolfCustoms** [comment]
![image](https://github.com/user-attachments/assets/d27fbc40-1fe6-41d5-a1b5-e9e7a2e04225)
