### ISSUE TITLE
Multiple/Duplicate Lines in def/cargo.sii

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#47]
**Describe the bug**
When multiple skin is added to the CargoContainer template it creates duplicate lines in the exportfile

**To Reproduce**
- The 1st time I helped a user with the mod it had - 4 lines (he had 6 skins in one CargoContainer)
- Used his saved ms2file, added the skins again ( 6 total )- outcome 5 duplicated lines in the file.

**Expected behavior**
Tried to check the **template.xml** how it write these, but no idea. It should _only_ write one line.

**Screenshots**
```javascript
SiiNunit
{
@include "cargo/maerskcargo1.sii"
@include "cargo/maerskcargo1.sii"
@include "cargo/maerskcargo1.sii"
@include "cargo/maerskcargo1.sii"
@include "cargo/maerskcargo1.sii"
}
```

**Desktop (please complete the following information):**
 - 2020.4 / 2020.5

**Additional context**
- These skins are using the same cargo created and same internal name.

_(tried to add png, jpg, zip to this issue, but it can't process the file...)_

> Something went really wrong, and we can't process that file.

**Comment by WerewolfCustoms** [comment]
I could not reproduce this bug. Works perfectly fine for me.
It might have been fixed while fixing other issues about cargo saving/loading...
