### ISSUE TITLE
UNABLE to edit or create new cargoes AND save them

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#49]
**Describe the bug**
**2020.5** - unable to edit or create new cargoes ... **SAVE** not possible

**To Reproduce**
1. create new cargo
2. Click on 'save'
3. **NOT** _saving_

**Expected behavior**
Save and let me continue to export the mod....

**Screenshots**
None

**Desktop (please complete the following information):**
 - Version [e.g. 22] Not sure what I'm suppose to write here ...desktop is reefering to..my PC ?

**Additional context**
Worked in previous version 2020.4
Tested a _template.xml_ made for **2020.5** in **2020.4** 
and it worked creating **AND** eidting cargoes so no issues with that one.

**MDModding** **CargoContainer**

**Comment by WerewolfCustoms** [comment]
Fixed, and also added a message box if things go wrong, so users know what's happening.
