### ISSUE TITLE
Add the option to make skins for the 2007 Nissan Qashqai ai traffic in the ETS2.

### ISSUE THREAD

**Issue by Nissantruck** [WerewolfCustoms/ModsStudio2IssueBoard#521]
feature request

I would like to see the Scs made ai car 2007 Nissan Qashqai in the MS2.So that i could make skins for it for the ETS2 ai traffic.
I did add the link for the cars picture in here.
[img]https://i.imgur.com/avj7fy1.png[/img]

**Comment by AdamLabrosse** [comment]
Nissan Qashqai added to ai traffic with issue #517 completed.
