### ISSUE TITLE
XML Feature - Reset to default DOESN'T work

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#524]
**Describe the bug**
as topic says...pressing the RESET button doesn't reset the edited files

**To Reproduce**
2. Click on any of the default trucks
3. edit and save it...  ALSO missing a saveoption to have it saved to the Documentsfolder instead of overwriting the existing default XML
4. press RESET button

**Expected behavior**
all back to default...didn't happen

**Screenshots**
![ms2_reset_vehicle_doesnt_apply](https://github.com/user-attachments/assets/876ab0ef-172b-4049-83d9-483eb2683f3e)

**Desktop (please complete the following information):**
 - Version [e.g. 2024.02PLUS]

**Additional context**
Consolecommand for sure did reset the files.....

**Comment by WerewolfCustoms** [comment]
@Mike7O 

In the new MS2, the reset to default will be removed. The way for users to "reset" their XML files will now be to use "update/refresh" option from the internet.

Let's see how that goes, and we can think about re-introducing the reset button.

For advanced users, there is still the option to use the MS2 command-line.
I have added an option to the command where you can now select the output folder so you do not overwrite your default files.
Add the -o  (-output) switch and voilà!

Example:
`write -d -o "D:\test\"`
