### ISSUE TITLE
Custom lightbox on Volvo FH4 Rework

### ISSUE THREAD

**Issue by chiky-chuky** [WerewolfCustoms/ModsStudio2IssueBoard#527]
**Describe the bug**
As SCS reworked the old Volvo FH16 2012, the cabin was modified and now there is a gap between the decal and the windshield when applying a custom decal from MS2. 

**To Reproduce**
1. Go to any service station or choose "upgrade" from the truck menu.
2. Click on accessories and choose a custom decal created with MS2.
3. The custom decal is not correctly aligned on the new cabin. 

**Expected behavior**
The custom decal should be applied correctly, leaving no open gaps on the cabin.

**Screenshots**
![ets2_20241114_103514_00](https://github.com/user-attachments/assets/757b5de7-36ec-4cbb-90c4-ff34fadc401a)

**Desktop (please complete the following information):**
 - Eurotruck Simulator v1.53

**Comment by chiky-chuky** [comment]
I know 1.53 is still in beta but, at this point in development. The issue most likely will carry to the full release so put this issue on the fridge till 1.53 is officially out.

**Comment by WerewolfCustoms** [comment]
![2024-12-20 21_33_31-Window](https://github.com/user-attachments/assets/a07b55e6-f8bc-40dd-a9a5-1aee1b8afca9)
