### ISSUE TITLE
Pre-made cargo types for cargo container

### ISSUE THREAD

**Issue by Kennet-H** [WerewolfCustoms/ModsStudio2IssueBoard#64]
It would be very nice and easy to create cargo containers and less time consuming if all the standard cargo types from ATS and ETS2 was already in the database of MS2.

**Comment by WerewolfCustoms** [comment]
Also, create script/tool to extract these from SCS base files

**Comment by pete-agreatguy** [comment]
Both ETS2 and ATS cargoes can be obtained from the following def files:

extracted ... \ def \ cargo

In the above directory with "[cargo].sui" ...

e.g.

```
cargo_data: cargo.apples
{
	name: "@@cn_apples@@"
	fragility: 0.4
	group[]: refrigerated
	volume: 2.6
	mass: 611.2
	unit_reward_per_km: 0.602
	unit_load_time: 78
	body_types[]: curtainside
	body_types[]: dryvan
}
```

So cargo name be extracted from either filename or from cargo_data within the sui file :)

**Comment by WerewolfCustoms** [comment]
This is ready to go in, together with other Cargo related issues. 👍
