### ISSUE TITLE
Add Cargo Icon for Cargo Containers [Suggestion]

### ISSUE THREAD

**Issue by Kennet-H** [WerewolfCustoms/ModsStudio2IssueBoard#68]

**Comment by Mike7O** [comment]
have done it to my files...but it probably needs to be made properly

**Comment by Mike7O** [comment]
lines I added to the **template.xml**

`	<Variable xsi:type="ScsImageSourceVariable">
	  <ChildVariables />
	  <Group>Cargo Icon Image</Group>
	  <Id>978f8c75-547f-4b4a-821b-70c000246605</Id>
	  <IsEnabled>true</IsEnabled>
	  <Name>CargoIcon</Name>
	  <Text>CargoIcon</Text>
      <Validators>	  
		<Validator xsi:type="NotEmptyValidator">
		<AdviceMessage>Please select an image for the cargo icon.</AdviceMessage>
		</Validator>
		<Validator xsi:type="ImageSizeValidator">
		  <Width>256</Width>
		  <Height>128</Height>
		</Validator>
		<Validator xsi:type="ImageFormatValidator">
		  <ImgFormat>Dds</ImgFormat>
		</Validator>
	  </Validators>
	  <AllowedExtensions>
	  <string>dds</string>
	  </AllowedExtensions>
	  <UseDefaultOptions>
       <string>cargoicon_example.dds</string>
      </UseDefaultOptions>
	  <PreloadDefault>false</PreloadDefault>	  
	</Variable>	`

and

```
  <BuildActions>
    <Action xsi:type="CreateDirectory">
      <Paths>
		**<string>material\ui\cargo_icons\</string>**
        <string>def\vehicle\trailer_cargo\{{ContainerInternalName}}\</string>
        <string>vehicle\trailer_eu\scs_gooseneck\ms2cargo\{{ContainerInternalName}}\</string>
        <string>vehicle\trailer_eu\scs_gooseneck\cargo\</string>
        <string>vehicle\trailer_eu\share\adr_labels\</string>
      </Paths>
```

`	<Action xsi:type="ImportImage">
	  <Source>{{CargoIcon}}</Source>
	  <Destination>\material\ui\cargo_icons\{{CARGO.CargoInternalName}}.dds</Destination>
		<OutputFormat>
		<Format>Dds</Format>
		<Preset>ScsIconImage</Preset>
		</OutputFormat>
	</Action>
		<Action xsi:type="GenerateTobjFile">
		 <FileName>\material\ui\cargo_icons\{{CARGO.CargoInternalName}}.tobj</FileName>
		 <Content>/material/ui/cargo_icons/{{CARGO.CargoInternalName}}.dds</Content>
		 <TobjType>UIIcon</TobjType>
		</Action>
	
	<Action xsi:type="WriteTextFile">
		<FileName>\material\ui\cargo_icons\{{CARGO.CargoInternalName}}.mat</FileName>
		<TextLines>
			<string></string>
			<string>material : "ui"</string>
			<string>{</string>
			<string>	texture : "{{CARGO.CargoInternalName}}.tobj"</string>
			<string>	texture_name : "texture"</string>
			<string>}</string>
		</TextLines>
		</Action>`

**Comment by Mike7O** [comment]
![cargo_icon](https://user-images.githubusercontent.com/66170614/180646711-ffb05da3-f91a-4be7-b572-a5cd40c9509b.jpg)

**Comment by WerewolfCustoms** [comment]
This is ready to go in, together with other Cargo related issues. 👍
