### ISSUE TITLE
Volvo DLC is not complete! And when come the Actros DLC into Mod Studio 2?

### ISSUE THREAD

**Issue by RubberDuck64** [WerewolfCustoms/ModsStudio2IssueBoard#69]
Hello Werewolf,
first let me tell you, you make a great job.
I have to tell you that the Volvo DLC is not complete. The "exhaust stakes" are not include!
And I have the question, when comes the support for the Mercedes Benz Actros DLC?

Thanks for your regard.
Greetings!

**Comment by WerewolfCustoms** [comment]
Added exhaust stacks to both Volvo trucks.
Added DLC parts for both Mercedes trucks.
Will be released in v.2020.10
