### ISSUE TITLE
Write tutorial for Vehicle XMLs

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#71]
Add website tutorial page for vehicle XMLs:
- [x] Explain what they are
- [x] Explain how to create new ones (Vehicle DB, and manual)
- [x] Add help button/links to relevant templates (vehicle variable)

**Comment by pete-agreatguy** [comment]
I don't mind taking this up :)

**Comment by pete-agreatguy** [comment]
What sort of web page do you want this written in? If not, I can write it up in MS Word and convert to PDF? I could add a video version at later date also.

**Comment by pete-agreatguy** [comment]
Documentation complete and live. Will learn how to add links to the app next.
