### ISSUE TITLE
Add additional accessories tooltips (images and descriptions)

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#77]
Add additional accessories tooltips (images and descriptions) to trailer accessories;

**Comment by pete-agreatguy** [comment]
@WerewolfCustoms This is now complete. Would you like this to be committed? Or shall I wait till I've completed other tasks?

**Comment by WerewolfCustoms** [comment]
@pete-agreatguy 
Commit your code changes often. (to your _WIP_ branch, that is).
Once commited, open a Pull Request for this task.

For other issues/tasks, create new branches, commit your code into those branches, and when done, open pull requests to get those branches reviewed and merged into _develop_ :)
