### ISSUE TITLE
Add option to traffic trailers to not include them in main game traffic

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#81]
Users often want their traffic trailers to only appear paired to their own traffic trucks.
It seems that users can prevent their traffic trailers from spawning randomly by not including them in the main traffic include file.
Add option to traffic trailer template to skip including that trailer. Good Pro feature.

**Comment by Mike7O** [comment]
I played around with this...
and it's working/probably not the best way - is the creation of a 
**traffic_trailer_type.ms2.sii**  file including the trailername for the custom traffictrailer
**traffic_storage_trailer_ms2.sii**
