### ISSUE TITLE
Vehicle Editor doesn't list a saved vehicle xml after saving it (needs auto refresh)

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#85]
MS2 version 2020.10

After Saving a new Vehicle Template using MS2 Vehicle Editor, the user is returned to the Vehicle Database window but this new entry will not show.

Temporary fix is to close the Vehicle Database window. Re-open it and the new entry is listed.

Suggest that the Vehicle Database window content is refreshed automatically after saving the new entry via Vehicle Editor.

Unsure if you would class this as a bug?

**Comment by WerewolfCustoms** [comment]
List is already re-loaded after adding new or editing current vehicle.
It was not re-loading after adding from mod/folder, and I have fixed this now.
