### ISSUE TITLE
Opening existing ms2 project file doesn't check for new/edited project templates

### ISSUE THREAD

**Issue by pete-agreatguy** [WerewolfCustoms/ModsStudio2IssueBoard#92]
**Describe the bug**
From the users perspective this is a bug. Ours, well, technically it isn't lol.

When a user opens up an existing MS2 project file, and that user has amended the template being used, any added or amended? content is not present due to using an old template.

e.g. One of our users had made a change to their Scania S Next Gen template (adding an accessory). When they loaded their saved project, they couldn't find the new accessory listed. 

**To Reproduce**
No errors. See example mentioned above.

**Expected behaviour**
Currently, when an MS2 project is opened, there is no check to see if the template used has been updated since being last open.

Lucasi worded this perfectly so I'm just going to copy and paste this here:

Currently, if you change anything in the accessories then you have to click the "delete image" button for all. Then go back to truck tab and click the truck you're working on then go back to the accessories tab and click "add image". That will reload the accessories list and keep your basic tab and truck image in tact.

**Screenshots**
n/a

**Desktop (please complete the following information):**
v2020.10+

**Additional context**
Does there need to be a check when opening an existing project file which uses a template that has been updated?

**Comment by WerewolfCustoms** [comment]
[Recap of the discussion we had on the live stream]

- This is not a bug, but it was made like this intentionally
- Indeed, this is not ideal and should be improved
- More complex saving/loading solution will require significant time & effort
- Will be done in the future, as time permits

**Comment by Wachert** [comment]
Idea for that: Realise an "import" function for older project files so the user gets a hint "there maybe issues with your mod or maybe there are newer accesories that you had not used before hands"
