### ISSUE TITLE
XML exporting issues

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#96]
When saving the custom xml, loaded from within the MS2 application _(load from mod/load from folder)_
you get the error seen on image:
https://discord.com/channels/611134812471820348/611170373773295616/814846752984399923

**Limitations of characters (12)**  and not able to have the **•**  makes it impossible to export as it should be.

**Comment by pete-agreatguy** [comment]
Duplicate bug report. This will get deleted.

See newer / more detailed issue 100 here:

https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues/100
